export const env = {
  PORT: process.env.PORT || '3001',
  REACT_APP_AUTH0_CLIENT_ID: (window as any).REACT_APP_AUTH0_CLIENT_ID || process.env.REACT_APP_AUTH0_CLIENT_ID,
  REACT_APP_AUTH0_DOMAIN: (window as any).REACT_APP_AUTH0_DOMAIN || process.env.REACT_APP_AUTH0_DOMAIN,
  REACT_APP_BACKEND_URL: (window as any).REACT_APP_BACKEND_URL || process.env.REACT_APP_BACKEND_URL,
  REACT_APP_AUTH0_CONNECTION: (window as any).REACT_APP_AUTH0_CONNECTION || process.env.REACT_APP_AUTH0_CONNECTION,
  REACT_APP_AUTH0_CDN: (window as any).REACT_APP_AUTH0_CDN || process.env.REACT_APP_AUTH0_CDN,
  REACT_APP_AUTH0_DEFAULT_AUDIENCE:
    (window as any).REACT_APP_AUTH0_DEFAULT_AUDIENCE || process.env.REACT_APP_AUTH0_DEFAULT_AUDIENCE,
}
