networkConcurrency: 16

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-exec.cjs
    spec: "@yarnpkg/plugin-exec"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@ojkelly/plugin-build.cjs
    spec: "https://github.com/ojkelly/yarn.build/releases/download/v0.9.53/plugin-build.js"

yarnPath: .yarn/releases/yarn-2.4.0.cjs


packageExtensions:
  react-dev-utils@*:
    peerDependencies:
      webpack: ^4.0.0
      typescript: ^2.7.0 
  "@node-ts/logger-core@*":
    dependencies:
      tslib: "^2.0.0"
  "@node-ts/logger-winston@*":
    dependencies:
      tslib: "^2.0.0"
  "graphql-amqp-subscriptions@*":
    dependencies:
      iterall: "*"
